version: "3"
services: 
  hub: 
    image: selenium/hub:3.141.59
    ports:
      - 4444:4444
  chrome: 
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    volumes:
      - /dev/shm:/dev/shm
  firefox: 
    image: selenium/node-firefox:3.141.59
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    volumes:
      - /dev/shm:/dev/shm
  search-module:
    image: gokul1712/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./search-result:/usr/share/udemy/test-output